# Generated by Django 4.0.2 on 2022-07-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0004_remove_addplot_status_remove_bookplot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookplot',
            name='plot_number',
            field=models.CharField(max_length=100),
        ),
    ]
