# Generated by Django 4.0.2 on 2022-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0005_alter_bookplot_plot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookplot',
            name='plc_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
