# Generated by Django 4.0.2 on 2022-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0006_alter_bookplot_plc_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
