# Generated by Django 4.0.2 on 2022-07-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0007_addplot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplot',
            name='total_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
