# Generated by Django 4.0.2 on 2022-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0008_addplot_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplot',
            name='plot_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
