# Generated by Django 4.0.2 on 2022-07-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0012_remove_customer_owner_customer_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='admin',
            new_name='owner',
        ),
    ]
