# Generated by Django 4.0.2 on 2022-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0014_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='superagent',
            name='ac_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superagent',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superagent',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superagent',
            name='holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superagent',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
