# Generated by Django 4.0.2 on 2022-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0015_superagent_ac_no_superagent_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookplot',
            name='no_of_emi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
