# Generated by Django 4.0.2 on 2022-08-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0016_bookplot_no_of_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='no_of_emi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
